### ISSUE TITLE
skyaware978 is 404

### ISSUE THREAD

**Issue by EasternPA** [mikenye/docker-piaware#112]
I lost the skyaware978 view on the piaware container web UI when the images moved to gchr. I had to manually copy `/usr/share/dump978-fa` into `/usr/share/skyaware978` to get it back. In https://github.com/sdr-enthusiasts/docker-baseimage/blob/main/Dockerfile.dump978-full#L41 you make the `/usr/share/dump978-fa` directory and copy `skyaware` into it, but you never make the `/usr/share/skyaware978` directory.

Once I manually copied `/usr/share/dump978-fa` back into `/usr/share/skyaware978` within the running container, the skyaware978 web UI came back no problem. I don't know what to fix in docker-baseimage to make that directory get created and populated.

**Comment by mikenye** [comment]
Hi @EasternPA,

I've put a fix for this in the Dockerfile (create a symlink instead of copy to keep the image size as small as possible).

Once PR #124 is merged, this issue will automatically be closed. After this, the new image will build (will take about 1-2 hours). Once complete, please pull the image and update your container.

Please feel free to re-open the issue if you're still having problems after that.

Thanks.
