### ISSUE TITLE
Add support for MLAT_RESULTS_ANON

### ISSUE THREAD

**Issue by YipYup** [mikenye/docker-piaware#139]
YipYup :
"Does the sdr-enthusiasts/docker-piaware support MLAT_RESULTS_ANON ? Just looking through the official config file options for piaware at https://flightaware.com/adsb/piaware/advanced_configuration
I'm interested in using them if possible to send to my mlathub instance, and having them show there."

@kx1t :
"I don’t think it does, but if you want to open an Issue on the docker-piaware repo, I’ll be happy to add that for you tomorrow"

**Comment by kx1t** [comment]
I did some research -- it looks like mlat_results_anon is default `enabled` when not specified. See 
https://flightaware.com/adsb/piaware/advanced_configuration

Do we still need this feature? Because exposing the parameter to be set would only add the capability to switch the feature OFF, and I think that may not be what you are looking for?

Tnx
